version: '3.8'

services:
  api:
    env_file:
      - .env
    container_name: api
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn main:app --proxy-headers --host 0.0.0.0 --reload'
    volumes:
      - ./:/home/backend:z
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:15-alpine
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db