wireguard_extra_peers:
  lukasz:
    ip: "10.0.0.2"
    public_key: "HGVT1rA1StFLn7DMRYnZbyl7OXOrwpZW70lnfZH+UAI="
  hubert:
    ip: "10.0.0.3"
    public_key: "KHkmjGt0XC+aqB4g6E4PWlbudLQhe+Yw3lkn1zVLL2M="
