---
- name: Playbook which runs some configuration of server
  gather_facts: no
  hosts: all
  roles:
    - name: os_config
      vars: 
        users: 
          - name: lszarecki
            state: present
          - name: jkoniuszewski
            state: present
          - name: devuser
            state: present
        packages:
          - tree
          - wireguard
          - resolvconf
          - traceroute
          - nftables
          - nautilus  # xrdp gui, open folders
          - xfce4-terminal  # xrdp gui, open folders
          - gnome-tweak-tool  # xrdp gui, open folders
    - name: wireguard
      become: yes

