---
- name: Playbook which runs some configuration of server
  gather_facts: no
  hosts: all
  roles:
    - name: os_config
    - name: wireguard
      become: yes
    - name: services
      become: yes
    - name: apps.install.python
      become: yes
