---
- name: Playbook which runs base configuration on NUC server
  gather_facts: no
  hosts: ovh_server
  roles:
    - name: os_config
      vars: 
        users: 
          - name: lszarecki
            state: present
          - name: jkoniuszewski
            state: present
        packages:
          - tree
          - wireguard
          - resolvconf

    - name: wireguard
