---

required_packages:
  - make
  - wget
  - build-essential
  - libncursesw5-dev
  - libssl-dev
  - libsqlite3-dev
  - tk-dev
  - libgdbm-dev
  - libc6-dev
  - libbz2-dev
  - libffi-dev
  - zlib1g-dev

desired_python_version: 3.11.4

python_download_urls:
  3.11.4:
    url: "https://www.python.org/ftp/python/3.11.4/Python-3.11.4.tar.xz"